
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - composer-network
    restart: unless-stopped


  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "5050:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - composer-network
    restart: unless-stopped

  fastapi:
    image: adilmm/scrape-comments:latest
    container_name: fastapi-scraper
    networks:
      - composer-network
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres

networks:
  composer-network:
    driver: bridge

volumes:
  postgres_data:
  keycloak_data: